Migrate to Chakra UI
hackclub/hack-as-a-service-v0 pull request #127
Opened 2021-05-04 02:37 UTC by anirudhb

Closes #97, mostly

Be warned this code is extremely hacky so be prepared to gouge your eyes out lol

2021-05-04 23:08 UTC, jasonappah requested changes
Everything else LGTM

2021-05-04 23:08 UTC, jasonappah commented on frontend/pages/teams/[id].tsx
> +      fetchApi(`/users/search?excluseSelf=true&q=${query}`).then((res) => {
```suggestion
      fetchApi(`/users/search?excludeSelf=true&q=${query}`).then((res) => {
```
guessing this was accidental

2021-05-04 23:10 UTC, jasonappah approved these changes

2021-05-05 00:14 UTC, sarthaktexas approved these changes

2021-05-05 00:31 UTC, cjdenio requested changes
Found some visual issues:
- the app component is too tall and doesn't show as a grid on the team page
- and the app component doesn't look great in dark mode
- also the "apps", "users", and "expenses" labels on the team dashboard are illegible in dark mode

<img width="1518" alt="Screen Shot 2021-05-04 at 8 29 45 PM" src="https://user-images.githubusercontent.com/34525547/117085341-785ac600-ad17-11eb-9a97-4cb50af2375b.png">
<img width="1599" alt="Screen Shot 2021-05-04 at 8 29 08 PM" src="https://user-images.githubusercontent.com/34525547/117085301-6416c900-ad17-11eb-9d40-c80bb342cd3a.png">

2021-05-05 02:47 UTC, cjdenio approved these changes
lgtm!

2021-05-05 02:54 UTC, merged