Build app environment page
hackclub/hack-as-a-service-v0 pull request #189
Opened 2021-05-07 22:03 UTC by cjdenio

This PR resolves #83 by making an environment page!

<img width="1576" alt="Screen Shot 2021-05-07 at 6 02 59 PM" src="https://user-images.githubusercontent.com/34525547/117512881-76367880-af5e-11eb-9ab5-f6f211545ec8.png">

2021-05-07 22:06 UTC, anirudhb requested changes
looks like there isn't a way to restart the app

2021-05-07 22:09 UTC, cjdenio commented
The app is restarted automatically after you click "save"
<img width="1152" alt="Screen Shot 2021-05-07 at 6 09 19 PM" src="https://user-images.githubusercontent.com/34525547/117513262-59e70b80-af5f-11eb-8630-748617b32344.png">

2021-05-07 22:21 UTC, jasonappah approved these changes

2021-05-08 00:34 UTC, anirudhb approved these changes

2021-05-08 00:37 UTC, merged