add darkmode toggle
hackclub/hack-as-a-service-v0 pull request #76
Opened 2021-04-30 14:39 UTC by bellesea

Closes #67

2021-04-30 14:41 UTC, cjdenio requested changes
lgtm, just one tiny change

(also run `yarn format:write`) to fix CI

2021-04-30 14:41 UTC, cjdenio commented on frontend/components/ColorButton.tsx
> +    <Box
`IconButton` might make more sense here

2021-04-30 14:42 UTC, bellesea commented on frontend/components/ColorButton.tsx
> +    <Box
ok! will make changes tmr :))

2021-04-30 14:50 UTC, bellesea commented on frontend/components/ColorButton.tsx
> +    <Box
changed my mind and decided i don't need sleep, made the edits!

2021-04-30 15:03 UTC, anirudhb requested changes

2021-04-30 15:03 UTC, anirudhb commented on frontend/components/ColorButton.tsx
> +      top: 26,
Please fix this now instead of later

2021-04-30 22:11 UTC, cfanoulis reviewed
a suggestion

2021-04-30 22:11 UTC, cfanoulis commented on frontend/components/ColorButton.tsx
> +    <Moon size={26} />
shouldn't this change according to mode?

2021-04-30 22:16 UTC, bellesea commented on frontend/components/ColorButton.tsx
> +    <Moon size={26} />
@cfanoulis do you mean the size of the moon?

2021-04-30 22:17 UTC, cfanoulis commented on frontend/components/ColorButton.tsx
> +    <Moon size={26} />
No, the icon itself. When it's light mode, it's a moon and when its dark mode its a sun.

2021-05-01 13:57 UTC, cfanoulis requested changes
feedback on icon changing handling

2021-05-01 13:57 UTC, cfanoulis commented on frontend/components/ColorButton.tsx
> +  const [colorMode] = useColorMode();
this can just be a prop on the button, instead of using the hook.

2021-05-01 16:23 UTC, anirudhb requested changes
nits

2021-05-01 16:23 UTC, anirudhb commented on frontend/components/ColorButton.tsx
> +function changeToggleButton({ ...props }) {
`export default function ColorButton` and remove the export below

2021-05-01 16:23 UTC, anirudhb commented on frontend/components/ColorButton.tsx
> +  }
```suggestion
  const icon = colorMode == "dark" ? <Sun /> : <Moon />;
```

2021-05-01 16:23 UTC, anirudhb commented on frontend/layouts/dashboard.tsx
> +      />
Maybe refactor this into the component itself and rename to `ColorSwitcher`

2021-05-01 23:51 UTC, anirudhb requested changes
lgtm! thanks for sticking with us Belle

2021-05-01 23:51 UTC, anirudhb commented on frontend/layouts/dashboard.tsx
> +import { useColorMode } from "theme-ui";
Remove this line

2021-05-02 01:55 UTC, bellesea commented
> lgtm! thanks for sticking with us Belle

thanks for helping me!

2021-05-02 01:58 UTC, anirudhb approved these changes

2021-05-02 01:58 UTC, merged