Added an error page & assets
hackclub/hack-as-a-service-v0 pull request #98
Opened 2021-05-01 20:23 UTC by l3gacyb3ta

The assets folder is now linked to /assets & the error page is now a catch-all page.

2021-05-01 20:24 UTC, l3gacyb3ta commented
Ah, According to checks, I need to format this..

2021-05-01 20:25 UTC, veritem requested changes
Run `yarn format:write` in fronted directory to fix ci

2021-05-01 20:29 UTC, l3gacyb3ta commented
Huh, is that the go code? I'll check.

2021-05-01 20:32 UTC, l3gacyb3ta commented
YES! I have fixed the code.

2021-05-01 20:38 UTC, l3gacyb3ta commented
Wait, there's some stuff I forgot, soooo

2021-05-01 20:45 UTC, cjdenio submitted a review, later dismissed

2021-05-01 20:45 UTC, cjdenio commented on main.go
> +	r.Use(static.ServeRoot("/assets", "./assets"))
Static assets should be served from the frontend rather than the API

2021-05-02 12:38 UTC, l3gacyb3ta commented on main.go
> +	r.Use(static.ServeRoot("/assets", "./assets"))
Ah, Ill fix that, that makes sense.

2021-05-02 16:26 UTC, anirudhb commented
Looks like this has conflicts now that #95 has been merged. Please rebase and fix those.

2021-05-02 22:29 UTC, l3gacyb3ta commented
Ok, I'll run the formaters

2021-05-02 22:33 UTC, l3gacyb3ta commented
YAY

2021-05-02 22:36 UTC, l3gacyb3ta commented
Eyyy errors merged

2021-05-02 22:36 UTC, l3gacyb3ta commented
Ugh formating

2021-05-02 22:38 UTC, l3gacyb3ta commented
Okie dokie, everything should be _fine_

2021-05-02 22:43 UTC, jasonappah requested changes
lgtm but please remove `frontend/package-lock.json` since we use yarn for dependency management, and also remove the `./hack-as-a-service` binary.

2021-05-02 22:45 UTC, l3gacyb3ta commented
Lol sorry for that, didnt mean to commit those.

2021-05-02 22:49 UTC, jasonappah requested changes
One more thing I didn't get the first time around, sorry, but it should be good for real this time!

2021-05-02 22:49 UTC, jasonappah commented on frontend/pages/teams/[id].tsx
> -  }, [id]);
Uh can you put this back? I'm guessing this was accidental lol

2021-05-02 22:50 UTC, veritem submitted a review, later dismissed

2021-05-02 22:50 UTC, veritem commented on main.go
> +	r.Use(static.ServeRoot("/assets", "./assets"))
Make sure to serve assets on frontend rather than backend

2021-05-02 22:53 UTC, l3gacyb3ta commented on frontend/pages/teams/[id].tsx
> -  }, [id]);
lol oops

2021-05-02 22:54 UTC, jasonappah commented on main.go
> +	r.Use(static.ServeRoot("/assets", "./assets"))
This line should be removed since you've added it to the frontend routes. Fix these last couple things and I'll merge!

2021-05-02 23:00 UTC, l3gacyb3ta commented
Please let this fixxx

2021-05-02 23:03 UTC, jasonappah approved these changes
Merging!

2021-05-02 23:05 UTC, merged